name = "GraphletCounting"
uuid = "652f9e12-ca7b-489b-a512-62ed18f481dc"
authors = ["sdgu"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
